# Generated by Claude Code and fixed/validated after by me (Christian G).
# Fixed(?): Moved logic_utils.py into the tests folder so the import line would work. Copying the functions check_guess and parse_guess may be
#           the better option here, so logic_utils can stay with app.py in the main folder.
# Validated: All tests passed. I'm going to move logic_utils back now...
from logic_utils import check_guess, parse_guess

def test_winning_guess():
    # If the secret is 50 and guess is 50, it should be a win
    result = check_guess(50, 50)
    # Fixed: For here and the following two functions, changed "assert result..." to two statements "assert result[0]" and
    #        "assert result[1]" to accurately check both values within "result".
    assert result[0] == "Win"
    assert result[1] == "🎉 Correct!"

def test_guess_too_high():
    # If secret is 50 and guess is 60, hint should be "Too High"
    result = check_guess(60, 50)
    assert result[0] == "Too High"
    assert result[1] == "📉 Go LOWER!"

def test_guess_too_low():
    # If secret is 50 and guess is 40, hint should be "Too Low"
    result = check_guess(40, 50)
    assert result[0] == "Too Low"
    assert result[1] == "📈 Go HIGHER!"

def test_invalid_guess_non_numeric():
    # Invalid guesses should not be counted as attempts
    ok, guess_int, err = parse_guess("abc")
    assert ok is False
    assert guess_int is None
    assert err == "That is not a number."

def test_invalid_guess_empty_string():
    ok, guess_int, err = parse_guess("")
    assert ok is False
    assert guess_int is None
    assert err == "Enter a guess."

# None is not a valid parameter value, so this will always fail.
# Fixed: Commenting it out for now.
# def test_invalid_guess_none():
#     ok, guess_int, err = parse_guess()
#     assert ok is False
#     assert guess_int is None
#     assert err == "Enter a guess."

def test_valid_guess():
    # Valid guesses should have ok=True
    ok, guess_int, err = parse_guess("42")
    assert ok is True
    assert guess_int == 42
    assert err is None

def test_valid_guess_decimal():
    # Decimal input should be converted to int
    ok, guess_int, err = parse_guess("42.7")
    assert ok is True
    assert guess_int == 42
    assert err is None
